services:
  node-red:
    image: nodered/node-red:3.1.9
    container_name: node-red
    restart: unless-stopped

    ports:
      - "1880:1880"

    volumes:
      - node_red_data:/data

    environment:
      - TZ=America/New_York

    networks:
      - traefik
      - default

    labels:
      - "traefik.enable=false"

networks:
  traefik:
    external: true

volumes:
  node_red_data:
    external: true
