services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped

    ports:
      - "0.0.0.0:1880:1880"

    networks:
      - node-red_lan
      - traefik

networks:
  node-red_lan:
    external: true
  traefik:
    external: true
