http:
  routers:
    immich:
      rule: "Host(`immich.cobblestone`)"
      entryPoints:
        - websecure
      service: immich
      tls:
        certResolver: cf

  services:
    immich:
      loadBalancer:
        servers:
          - url: "http://immich-server:2283"
