http:
  routers:
    node-red:
      rule: "Host(`node-red.cobblestone`)"
      entryPoints:
        - web
      service: node-red

  services:
    node-red:
      loadBalancer:
        servers:
          - url: "http://node-red:1880"
